fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.1.6"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
      - id: ruff-format
  # Changes tabs to spaces
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
    - id: remove-tabs
      exclude: ^(docs|Makefile)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.770'
    hooks:
    -   id: mypy
